version: 2.1
  jobs:
    build:
      - run: git clone https://github.com/ryolairyolai/test
      - run: cd test/
      - run: git remote add upstream https://github.com/na-ka-mu-ra-/tes
      - run: git checkout master
      - run: git push origin master

