version: 2
jobs:
  build:
    machine: true
    environment:
      FORK="https://github.com/ryolairyolai/test"
      ORIG="https://github.com/na-ka-mu-ra-/test"
      CD=test
      EXEC=ryolairyolai
    steps:
      - add_ssh_keys: 
          fingerprints:
            - "52:d6:3d:21:10:e2:d2:54:82:37:84:43:92:a5:5a:62"
      - checkout
      - run: git clone $FORK
      - run: git config --global user.name $EXEC
      - run: cd  $CD
      - run: git remote add upstream $ORIG
      - run: git checkout master
      - run: git pull --no-edit upstream master
      - run: git push origin master

