version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git config --global user.name "ryolailai"
      - run: git clone https://github.com/ryolairyolai/test
      - run: cd test/
      - run: git remote add upstream https://github.com/na-ka-mu-ra-/test
      - run: git checkout master
      - run: git pull upstream master
      - run: git push origin master

